import { useEffect, useRef, useState, type ReactNode } from 'react'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm, useWatch } from 'react-hook-form'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { toast } from 'react-toastify'
import { getRamas } from '../../api/catalogosApi'
import { toApiError } from '../../api/errors'
import { applyDrfErrors } from '../forms/applyDrfErrors'
import { FormActions } from '../forms/FormActions'
import { FormErrorSummary } from '../forms/FormErrorSummary'
import { FormField } from '../forms/FormField'
import { FormSelect } from '../forms/FormSelect'
import { UnsavedChangesDialog } from '../forms/UnsavedChangesDialog'
import { useUnsavedChanges } from '../forms/useUnsavedChanges'
import { allowDirtyNavigation } from '../forms/useDirtyNavigationGuard'
import { PaginatedOptionPicker } from './PaginatedOptionPicker'
import { adultoUnidadSchema, miembroSchema, reasignacionSchema, subgrupoSchema, unidadSchema, type AdultoUnidadFormValues, type MiembroFormValues, type ReasignacionFormValues, type SubgrupoFormValues, type UnidadFormValues } from './structuralSchemas'
import { useAdultoRolCommand, useAdultoRolQuery, useMiembroCommand, useMiembroQuery, useOptionQuery, useSubgrupoCommand, useSubgrupoQuery, useUnidadCommand } from './useStructuralQueries'
import { useUnidadDetailQuery } from './useUnidadesQuery'

const asId = (raw?: string) => Number(raw) || 0
const summary = (errors: Record<string, { message?: string } | undefined>, global: string[]) => [...Object.entries(errors).flatMap(([name, value]) => value?.message ? [{ name, message: value.message }] : []), ...global.map((message) => ({ message }))]

export function ConfirmingBackLink({ dirty }: { dirty: boolean }) {
  const [open, setOpen] = useState(false); const triggerRef = useRef<HTMLButtonElement>(null); const navigate = useNavigate()
  if (!dirty) return <Link className="grupos-back-link" to="/app/unidades">← Volver</Link>
  return <><button ref={triggerRef} className="grupos-back-link" type="button" onClick={() => setOpen(true)}>← Volver</button><UnsavedChangesDialog open={open} restoreFocusRef={triggerRef} onContinueEditing={() => setOpen(false)} onDiscard={() => { allowDirtyNavigation(); navigate('/app/unidades') }} /></>
}
function Page({ title, dirty, children }: { title: string; dirty?: boolean; children: ReactNode }) { const unsavedChangesDialog = useUnsavedChanges(Boolean(dirty)); return <>{unsavedChangesDialog}<section className="home-feed form-page" aria-labelledby="structural-title"><ConfirmingBackLink dirty={Boolean(dirty)} /><article className="home-card"><h1 id="structural-title">{title}</h1>{children}</article></section></> }
function State({ message }: { message: string }) { return <Page title="Gestión estructural"><p role="alert">{message}</p></Page> }
function useServerErrors<T extends Record<string, unknown>>(form: ReturnType<typeof useForm<T>>, fields: readonly (keyof T & string)[]) { const [errors, setErrors] = useState<string[]>([]); return { errors, handle(error: unknown) { const api = toApiError(error); setErrors(applyDrfErrors(api.error.details, form.setError, fields as never)) } } }
function useRamas() { const [ramas, setRamas] = useState<Array<{ id: number; nombre: string }>>([]); useEffect(() => { void getRamas({ activa: true }).then((r) => setRamas(r.data)).catch(() => setRamas([])) }, []); return ramas }

export function UnidadFormPage() {
  const { unidadId } = useParams(); const [searchParams] = useSearchParams(); const id = asId(unidadId); const editing = id > 0; const detail = useUnidadDetailQuery(id); const command = useUnidadCommand(); const navigate = useNavigate(); const [page, setPage] = useState(1); const [search, setSearch] = useState('')
  const form = useForm<UnidadFormValues>({ resolver: zodResolver(unidadSchema), defaultValues: { grupo: asId(searchParams.get('grupo_id') ?? undefined), rama: 0, nombre: '', tipo_composicion: '', estado: 'ACTIVA', cupo_maximo: null } }); const server = useServerErrors(form, ['grupo', 'rama', 'nombre', 'tipo_composicion', 'estado', 'cupo_maximo']);
  const groups = useOptionQuery('grupos', { page, search }); const ramas = useRamas(); const group = useWatch({ control: form.control, name: 'grupo' })
  useEffect(() => { const unit = detail.data?.data; if (unit) form.reset({ grupo: unit.grupo, rama: unit.rama, nombre: unit.nombre, tipo_composicion: unit.tipo_composicion, estado: unit.estado as UnidadFormValues['estado'], cupo_maximo: unit.cupo_maximo }) }, [detail.data, form])
  if (editing && detail.isLoading) return <State message="Cargando unidad…" />
  if (editing && (detail.isError || !detail.data?.data)) return <State message="La unidad no está disponible o no tienes acceso." />
  if (editing && !detail.data?.meta?.permissions?.can_edit) return <State message="El backend no permite editar esta unidad." />
  const unit = detail.data?.data
  return <Page title={editing ? 'Editar unidad' : 'Nueva unidad'} dirty={form.formState.isDirty}><form className="domain-form" noValidate onSubmit={form.handleSubmit(async (values) => { try { const response = await command.mutateAsync({ id: editing ? id : undefined, values }); toast.success('Unidad guardada.'); allowDirtyNavigation(); navigate(`/app/unidades/${(response as { data?: { id?: number } }).data?.id ?? id}`) } catch (error) { server.handle(error) } })}><FormErrorSummary errors={summary(form.formState.errors, server.errors)} />{editing ? <p className="form-context">Grupo: {unit?.grupo_nombre} · Rama: {unit?.rama_nombre}. Este contexto no se puede cambiar.</p> : <><PaginatedOptionPicker label="Grupo" value={group || null} onChange={(value) => form.setValue('grupo', value, { shouldDirty: true, shouldValidate: true })} query={groups} onSearch={setSearch} onPageChange={(delta) => setPage((current) => Math.max(1, current + delta))} error={form.formState.errors.grupo?.message} /><FormSelect label="Rama" options={[{ value: '', label: 'Selecciona una rama' }, ...ramas.map((rama) => ({ value: String(rama.id), label: rama.nombre }))]} {...form.register('rama', { valueAsNumber: true })} error={form.formState.errors.rama?.message} /></>}<div className="form-grid"><FormField label="Nombre" {...form.register('nombre')} error={form.formState.errors.nombre?.message} /><FormSelect label="Estado" options={[{ value: 'ACTIVA', label: 'Activa' }, { value: 'INACTIVA', label: 'Inactiva' }]} {...form.register('estado')} error={form.formState.errors.estado?.message} /><FormSelect label="Composición" options={[{ value: '', label: 'La definida por la rama' }, { value: 'SOLO_HOMBRES', label: 'Solo hombres' }, { value: 'SOLO_MUJERES', label: 'Solo mujeres' }, { value: 'MIXTA', label: 'Mixta' }]} {...form.register('tipo_composicion')} error={form.formState.errors.tipo_composicion?.message} /><FormField label="Cupo máximo" type="number" {...form.register('cupo_maximo', { setValueAs: (value) => value === '' ? null : Number(value) })} error={form.formState.errors.cupo_maximo?.message} /></div><FormActions isSubmitting={command.isPending} submitLabel="Guardar" /></form></Page>
}

export function SubgrupoFormPage() {
  const { subgrupoId, unidadId } = useParams(); const id = asId(subgrupoId); const editing = id > 0; const detail = useSubgrupoQuery(id); const command = useSubgrupoCommand(); const navigate = useNavigate(); const form = useForm<SubgrupoFormValues>({ resolver: zodResolver(subgrupoSchema), defaultValues: { unidad: asId(unidadId), nombre: '', lider_juvenil: null } }); const server = useServerErrors(form, ['unidad', 'nombre', 'lider_juvenil']);
  const leaderOptions = useOptionQuery('beneficiarios', { subgrupo_id: id }); const leader = useWatch({ control: form.control, name: 'lider_juvenil' }); useEffect(() => { const subgroup = detail.data?.data; if (subgroup) form.reset(subgroup) }, [detail.data, form])
  if (editing && detail.isLoading) return <State message="Cargando subgrupo…" />
  if (editing && (detail.isError || !detail.data?.data)) return <State message="El subgrupo no está disponible o no tienes acceso." />
  if (editing && !detail.data?.meta?.permissions?.can_assign_leader) return <State message="El backend no permite editar este subgrupo." />
  return <Page title={editing ? 'Editar subgrupo' : 'Nuevo subgrupo'} dirty={form.formState.isDirty}><form className="domain-form" noValidate onSubmit={form.handleSubmit(async (values) => { try { const response = await command.mutateAsync({ id: editing ? id : undefined, values }) as { data?: { unidad?: number } }; toast.success('Subgrupo guardado.'); allowDirtyNavigation(); navigate(`/app/unidades/${response.data?.unidad ?? detail.data?.data.unidad ?? asId(unidadId)}`) } catch (error) { server.handle(error) } })}><FormErrorSummary errors={summary(form.formState.errors, server.errors)} /><FormField label="Nombre" {...form.register('nombre')} error={form.formState.errors.nombre?.message} />{editing ? <PaginatedOptionPicker label="Líder juvenil" value={leader} onChange={(value) => form.setValue('lider_juvenil', value, { shouldDirty: true })} query={leaderOptions} error={form.formState.errors.lider_juvenil?.message} /> : <p className="form-context">El liderazgo se asigna después de crear el subgrupo y agregar integrantes.</p>}<FormActions isSubmitting={command.isPending} submitLabel="Guardar" /></form></Page>
}

export function MiembroFormPage() {
  const { miembroId, subgrupoId, unidadId } = useParams(); const id = asId(miembroId); const editing = id > 0; const member = useMiembroQuery(id); const command = useMiembroCommand(); const navigate = useNavigate(); const [confirming, setConfirming] = useState(false); const form = useForm<MiembroFormValues | ReasignacionFormValues>({ resolver: zodResolver(editing ? reasignacionSchema : miembroSchema), defaultValues: editing ? { subgrupo: 0 } : { subgrupo: asId(subgrupoId), beneficiario: 0 } }); const server = useServerErrors(form, (editing ? ['subgrupo'] : ['subgrupo', 'beneficiario']) as never);
  const options = useOptionQuery(editing ? 'destinos' : 'beneficiarios', editing ? { miembro_id: id } : { unidad_id: asId(unidadId) }); const parentSubgrupo = useSubgrupoQuery(member.data?.data.subgrupo ?? 0); const selected = useWatch({ control: form.control, name: editing ? 'subgrupo' : 'beneficiario' })
  if (editing && member.isLoading) return <State message="Cargando membresía…" />
  if (editing && (member.isError || !member.data?.data || !member.data.meta?.permissions?.can_reassign)) return <State message="No puedes reasignar esta membresía." />
  async function save(values: MiembroFormValues | ReasignacionFormValues) { if (editing && !confirming) { setConfirming(true); return } try { await command.mutateAsync({ id: editing ? id : undefined, values }); toast.success('Membresía guardada.'); allowDirtyNavigation(); navigate(`/app/unidades/${asId(unidadId) || parentSubgrupo.data?.data.unidad || ''}`) } catch (error) { server.handle(error) } }
  return <Page title={editing ? 'Reasignar integrante' : 'Agregar integrante'} dirty={form.formState.isDirty}><form className="domain-form" noValidate onSubmit={form.handleSubmit(save)}><FormErrorSummary errors={summary(form.formState.errors, server.errors)} />{editing ? <p>Integrante: {member.data?.data.beneficiario_persona_nombre}</p> : null}<PaginatedOptionPicker label={editing ? 'Subgrupo de destino' : 'Beneficiario'} value={selected || null} onChange={(value) => form.setValue(editing ? 'subgrupo' : 'beneficiario', value, { shouldDirty: true })} query={options} error={editing ? form.formState.errors.subgrupo?.message : (form.formState.errors as { beneficiario?: { message?: string } }).beneficiario?.message} />{confirming ? <div className="confirm-dialog__inline" role="alert"><p>Confirma la reasignación entre la unidad de origen y destino.</p><button type="submit">Confirmar reasignación</button><button type="button" onClick={() => setConfirming(false)}>Cancelar</button></div> : <FormActions isSubmitting={command.isPending} submitLabel={editing ? 'Reasignar integrante' : 'Agregar integrante'} />}</form></Page>
}

export function AdultoRolFormPage() {
  const { asignacionId, unidadId } = useParams(); const id = asId(asignacionId); const editing = id > 0; const detail = useAdultoRolQuery(id); const command = useAdultoRolCommand(); const navigate = useNavigate(); const form = useForm<AdultoUnidadFormValues>({ resolver: zodResolver(adultoUnidadSchema), defaultValues: { unidad: asId(unidadId), adulto: 0, rol: 'ASISTENTE' } }); const server = useServerErrors(form, ['unidad', 'adulto', 'rol']);
  const adults = useOptionQuery('adultos', { unidad_id: editing ? detail.data?.data.unidad : asId(unidadId) }); const adult = useWatch({ control: form.control, name: 'adulto' }); useEffect(() => { const assignment = detail.data?.data; if (assignment) form.reset({ unidad: assignment.unidad, adulto: assignment.adulto, rol: assignment.rol as AdultoUnidadFormValues['rol'] }) }, [detail.data, form])
  if (editing && detail.isLoading) return <State message="Cargando asignación…" />
  if (editing && (detail.isError || !detail.data?.data || !detail.data.meta?.permissions?.can_edit_role)) return <State message="No puedes editar esta asignación." />
  return <Page title={editing ? 'Editar rol adulto' : 'Asignar adulto'} dirty={form.formState.isDirty}><form className="domain-form" noValidate onSubmit={form.handleSubmit(async (values) => { try { const response = await command.mutateAsync({ id: editing ? id : undefined, values }) as { data?: { unidad?: number } }; toast.success('Asignación guardada.'); allowDirtyNavigation(); navigate(`/app/unidades/${response.data?.unidad ?? detail.data?.data.unidad ?? asId(unidadId)}`) } catch (error) { server.handle(error) } })}><FormErrorSummary errors={summary(form.formState.errors, server.errors)} />{editing ? <p>Adulto: {detail.data?.data.adulto_persona_nombre}</p> : <PaginatedOptionPicker label="Adulto" value={adult || null} onChange={(value) => form.setValue('adulto', value, { shouldDirty: true })} query={adults} error={form.formState.errors.adulto?.message} />}<FormSelect label="Rol" options={[{ value: 'RESPONSABLE', label: 'Responsable' }, { value: 'ASISTENTE', label: 'Asistente' }, { value: 'COLABORADOR', label: 'Colaborador' }]} {...form.register('rol')} error={form.formState.errors.rol?.message} /><FormActions isSubmitting={command.isPending} submitLabel="Guardar" /></form></Page>
}
