# Generated by Django 5.2.13 on 2026-04-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('edad_minima', models.PositiveSmallIntegerField()),
                ('edad_maxima', models.PositiveSmallIntegerField()),
                ('composicion_permitida', models.CharField(choices=[('MIXTA', 'Mixta'), ('SOLO_HOMBRES', 'Solo hombres'), ('SOLO_MUJERES', 'Solo mujeres')], default='MIXTA', max_length=20)),
                ('nomenclatura_subgrupos', models.CharField(max_length=40)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rama',
                'verbose_name_plural': 'Ramas',
                'ordering': ['edad_minima', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='catalogos.distrito')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'distrito'), name='uq_zona_nombre_distrito')],
            },
        ),
    ]
