# Generated by Django 5.2.13 on 2026-04-22

import django.db.models.deletion
from django.db import migrations, models


def backfill_distrito_zona(apps, schema_editor):
    Zona = apps.get_model("catalogos", "Zona")
    Distrito = apps.get_model("catalogos", "Distrito")

    fallback_zona, _ = Zona.objects.get_or_create(nombre="Zona Metropolitana")
    Distrito.objects.filter(zona__isnull=True).update(zona=fallback_zona)


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0002_remove_zona_uq_zona_nombre_distrito_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_distrito_zona, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="distrito",
            name="zona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distritos",
                to="catalogos.zona",
            ),
        ),
    ]
