# Generated by Django 5.2.13 on 2026-04-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComiteGrupoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('SECRETARIO', 'Secretario/a'), ('TESORERO', 'Tesorero/a')], max_length=20)),
            ],
            options={
                'verbose_name': 'Cargo de comite',
                'verbose_name_plural': 'Cargos de comite',
            },
        ),
        migrations.CreateModel(
            name='ConsejoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acta_nombramiento', models.FileField(blank=True, upload_to='actas_consejo/')),
            ],
            options={
                'verbose_name': 'Consejo de grupo',
                'verbose_name_plural': 'Consejos de grupo',
            },
        ),
        migrations.CreateModel(
            name='GrupoScout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_oficial', models.CharField(max_length=180, unique=True)),
                ('tipo_grupo', models.CharField(choices=[('CONFESIONAL', 'Confesional'), ('PLURICONFESIONAL', 'Pluriconfesional')], max_length=20)),
                ('religion', models.CharField(blank=True, max_length=80)),
                ('estado_vigencia', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('DISUELTO', 'Disuelto'), ('OBSERVACION', 'Observacion')], default='ACTIVO', max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=80)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('minimo_miembros_calculado', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Grupo Scout',
                'verbose_name_plural': 'Grupos Scout',
                'ordering': ['nombre_oficial'],
            },
        ),
        migrations.CreateModel(
            name='InstitucionPatrocinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(max_length=60)),
                ('representante_nombre', models.CharField(max_length=150)),
                ('representante_telefono', models.CharField(max_length=30)),
                ('representante_email', models.EmailField(max_length=254)),
                ('fecha_inicio_convenio', models.DateField()),
                ('fecha_fin_convenio', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Institucion patrocinante',
                'verbose_name_plural': 'Instituciones patrocinantes',
                'ordering': ['nombre'],
            },
        ),
    ]
