# Generated by Django 5.2.13 on 2026-04-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comitegrupocargo',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_comite', to='personas.apoderado'),
        ),
        migrations.AddField(
            model_name='consejogrupo',
            name='responsable_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consejos_de_grupo', to='personas.adulto'),
        ),
        migrations.AddField(
            model_name='gruposcout',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='catalogos.distrito'),
        ),
        migrations.AddField(
            model_name='gruposcout',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='catalogos.zona'),
        ),
        migrations.AddField(
            model_name='consejogrupo',
            name='grupo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consejo', to='organizacion.gruposcout'),
        ),
        migrations.AddField(
            model_name='comitegrupocargo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_cargos', to='organizacion.gruposcout'),
        ),
        migrations.AddField(
            model_name='institucionpatrocinante',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituciones_patrocinantes', to='organizacion.gruposcout'),
        ),
        migrations.AddConstraint(
            model_name='comitegrupocargo',
            constraint=models.UniqueConstraint(fields=('grupo', 'rol'), name='uq_comite_rol_por_grupo'),
        ),
    ]
