# Generated by Django 5.2.13 on 2026-04-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_composicion', models.CharField(blank=True, choices=[('MIXTA', 'Mixta'), ('SOLO_HOMBRES', 'Solo hombres'), ('SOLO_MUJERES', 'Solo mujeres')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=10)),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='organizacion.gruposcout')),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='catalogos.rama')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('lider_juvenil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgrupos_liderados', to='personas.beneficiario')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='unidades.unidad')),
            ],
            options={
                'verbose_name': 'Subgrupo',
                'verbose_name_plural': 'Subgrupos',
            },
        ),
        migrations.CreateModel(
            name='AdultoUnidadRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('RESPONSABLE', 'Responsable de unidad'), ('ASISTENTE', 'Asistente'), ('COLABORADOR', 'Colaborador')], max_length=20)),
                ('adulto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_unidad', to='personas.adulto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_adulto', to='unidades.unidad')),
            ],
            options={
                'verbose_name': 'Rol adulto en unidad',
                'verbose_name_plural': 'Roles adultos en unidad',
            },
        ),
        migrations.CreateModel(
            name='SubgrupoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_subgrupo', to='personas.beneficiario')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='unidades.subgrupo')),
            ],
            options={
                'verbose_name': 'Miembro de subgrupo',
                'verbose_name_plural': 'Miembros de subgrupo',
                'constraints': [models.UniqueConstraint(fields=('subgrupo', 'beneficiario'), name='uq_subgrupo_beneficiario')],
            },
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('grupo', 'nombre'), name='uq_unidad_nombre_por_grupo'),
        ),
        migrations.AddConstraint(
            model_name='subgrupo',
            constraint=models.UniqueConstraint(fields=('unidad', 'nombre'), name='uq_subgrupo_nombre_por_unidad'),
        ),
        migrations.AddConstraint(
            model_name='adultounidadrol',
            constraint=models.UniqueConstraint(fields=('unidad', 'adulto', 'rol'), name='uq_adulto_rol_unidad'),
        ),
        migrations.AddConstraint(
            model_name='adultounidadrol',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'RESPONSABLE')), fields=('unidad', 'rol'), name='uq_responsable_por_unidad'),
        ),
    ]
