# Generated by Django 5.2.13 on 2026-04-22 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zona',
            name='uq_zona_nombre_distrito',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='distrito',
        ),
        migrations.AddField(
            model_name='distrito',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distritos', to='catalogos.zona'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='distrito',
            constraint=models.UniqueConstraint(fields=('nombre', 'zona'), name='uq_distrito_nombre_zona'),
        ),
    ]
