# Generated by Django 5.2.13 on 2026-04-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formacion', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultogradoformacion',
            name='adulto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_formacion', to='personas.adulto'),
        ),
        migrations.AddConstraint(
            model_name='gradoformacion',
            constraint=models.UniqueConstraint(fields=('nivel', 'especialidad'), name='uq_grado_nivel_especialidad'),
        ),
        migrations.AddField(
            model_name='adultogradoformacion',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adultos', to='formacion.gradoformacion'),
        ),
        migrations.AddConstraint(
            model_name='adultogradoformacion',
            constraint=models.UniqueConstraint(fields=('adulto', 'grado'), name='uq_adulto_grado_formacion'),
        ),
    ]
