# Generated by Django 5.2.13 on 2026-04-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdultoGradoFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_obtencion', models.DateField()),
            ],
            options={
                'verbose_name': 'Formacion de adulto',
                'verbose_name_plural': 'Formaciones de adulto',
            },
        ),
        migrations.CreateModel(
            name='GradoFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel', models.CharField(max_length=60)),
                ('especialidad', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Grado de formacion',
                'verbose_name_plural': 'Grados de formacion',
                'ordering': ['nivel', 'especialidad'],
            },
        ),
    ]
