# Generated by Django 5.2.13 on 2026-04-18 00:00

import common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol_principal', models.CharField(choices=[('GUIA', 'Guia'), ('DIRIGENTE', 'Dirigente'), ('APODERADO', 'Apoderado'), ('RESP_GRUPO', 'Responsable de grupo'), ('COLABORADOR', 'Colaborador')], max_length=20)),
                ('certificado_inhabilidades', models.FileField(upload_to='certificados_inhabilidades/')),
                ('certificado_vigencia_hasta', models.DateField()),
            ],
            options={
                'verbose_name': 'Adulto',
                'verbose_name_plural': 'Adultos',
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('es_miembro_comite', models.BooleanField(default=False)),
                ('rol_comite', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[common.validators.validar_rut])),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('OT', 'Otro')], max_length=2)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='ApoderadoBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor'), ('ABUELO', 'Abuelo/a'), ('OTRO', 'Otro')], max_length=20)),
                ('autoriza_salidas_terreno', models.BooleanField(default=False)),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_beneficiarios', to='personas.apoderado')),
            ],
            options={
                'verbose_name': 'Relacion apoderado-beneficiario',
                'verbose_name_plural': 'Relaciones apoderado-beneficiario',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_ingreso', models.DateField()),
                ('progresion_scout', models.TextField(blank=True)),
                ('rama_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiarios', to='catalogos.rama')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
    ]
