# Generated by Django 5.2.13 on 2026-04-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiarios', to='unidades.unidad'),
        ),
        migrations.AddField(
            model_name='apoderadobeneficiario',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_apoderados', to='personas.beneficiario'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apoderado', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='adulto',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adulto', to='personas.persona'),
        ),
        migrations.AddConstraint(
            model_name='apoderadobeneficiario',
            constraint=models.UniqueConstraint(fields=('apoderado', 'beneficiario'), name='uq_apoderado_beneficiario'),
        ),
    ]
