# Generated by Django 5.2.13 on 2026-05-28 19:58

import django.db.models.deletion
from django.db import migrations, models


AREAS_DESARROLLO = [
    {
        'codigo': 'CORPORALIDAD',
        'nombre': 'Corporalidad',
        'definicion': 'Se enfoca en el desarrollo del cuerpo, asumiendo la responsabilidad personal en su crecimiento y salud.',
        'personaje_simbolo': 'Bagheera',
        'lema': 'Fuertes y sanos',
    },
    {
        'codigo': 'CREATIVIDAD',
        'nombre': 'Creatividad',
        'definicion': 'Busca la estimulacion de la creatividad, la inteligencia y la capacidad de innovar y aventurar.',
        'personaje_simbolo': 'Kaa',
        'lema': 'Ingeniosos',
    },
    {
        'codigo': 'CARACTER',
        'nombre': 'Caracter',
        'definicion': 'Se centra en la formacion del caracter, trabajando la voluntad, la autonomia y el compromiso con los propios valores.',
        'personaje_simbolo': 'Baloo',
        'lema': 'Sabios',
    },
    {
        'codigo': 'AFECTIVIDAD',
        'nombre': 'Afectividad',
        'definicion': 'Trata sobre la orientacion de los afectos, buscando el equilibrio emocional y la madurez en las relaciones.',
        'personaje_simbolo': 'Raksha',
        'lema': 'Afectuosos',
    },
    {
        'codigo': 'SOCIABILIDAD',
        'nombre': 'Sociabilidad',
        'definicion': 'Apunta al encuentro con los otros, el aprendizaje de la libertad solidaria y el servicio a la comunidad.',
        'personaje_simbolo': 'Akela',
        'lema': 'Generosos',
    },
    {
        'codigo': 'ESPIRITUALIDAD',
        'nombre': 'Espiritualidad',
        'definicion': 'Se refiere a la busqueda de Dios y la dimension trascendente de la vida, integrando la fe en la conducta cotidiana.',
        'personaje_simbolo': 'Francisco de Asis',
        'lema': '',
    },
]


def seed_areas_desarrollo(apps, schema_editor):
    AreaDesarrollo = apps.get_model('personas', 'AreaDesarrollo')
    for area in AREAS_DESARROLLO:
        AreaDesarrollo.objects.update_or_create(codigo=area['codigo'], defaults=area)


def unseed_areas_desarrollo(apps, schema_editor):
    AreaDesarrollo = apps.get_model('personas', 'AreaDesarrollo')
    AreaDesarrollo.objects.filter(codigo__in=[area['codigo'] for area in AREAS_DESARROLLO]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('definicion', models.TextField()),
                ('personaje_simbolo', models.CharField(blank=True, max_length=80)),
                ('lema', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Area de desarrollo',
                'verbose_name_plural': 'Areas de desarrollo',
                'ordering': ['nombre'],
            },
        ),
        migrations.RunPython(seed_areas_desarrollo, unseed_areas_desarrollo),
        migrations.RemoveField(
            model_name='beneficiario',
            name='progresion_scout',
        ),
        migrations.CreateModel(
            name='RegistroProgresionScout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('INICIO_CICLO', 'Inicio ciclo'), ('DURANTE_CICLO', 'Durante el ciclo'), ('FINAL_CICLO', 'Final de ciclo')], max_length=20)),
                ('texto', models.TextField()),
                ('areas', models.ManyToManyField(related_name='registros_progresion', to='personas.areadesarrollo')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_progresion', to='personas.beneficiario')),
            ],
            options={
                'verbose_name': 'Registro de progresion scout',
                'verbose_name_plural': 'Registros de progresion scout',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
