# Generated by Django 5.2.13 on 2026-05-08 15:07

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposcout',
            name='logo',
            field=models.CharField(blank=True, max_length=500, validators=[common.validators.validar_url_o_ruta_logo]),
        ),
        migrations.AddField(
            model_name='institucionpatrocinante',
            name='logo',
            field=models.CharField(blank=True, max_length=500, validators=[common.validators.validar_url_o_ruta_logo]),
        ),
    ]
