# Generated by Django 5.2.13 on 2026-05-25 22:55

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personas/fotos/', validators=[common.validators.validar_foto_persona]),
        ),
    ]
