# Generated by Django 5.2.13 on 2026-08-12

from django.db import migrations, models


SPECIAL_ROLES = ("APODERADO", "RESP_GRUPO", "COLABORADOR")


def regularize_adult_roles(apps, schema_editor):
    Adulto = apps.get_model("personas", "Adulto")

    # The former state used GUIA while the application choice is GUIADORA.
    Adulto.objects.filter(rol_principal="GUIA").update(rol_principal="GUIADORA")

    assigned_adults = Adulto.objects.filter(asignaciones_unidad__isnull=False).exclude(
        rol_principal__in=SPECIAL_ROLES
    )
    assigned_adults.filter(persona__sexo="F").update(rol_principal="GUIADORA")
    assigned_adults.filter(persona__sexo="M").update(rol_principal="DIRIGENTE")


def reverse_regularize_adult_roles(apps, schema_editor):
    Adulto = apps.get_model("personas", "Adulto")

    # Regularization is lossy, but GUIADORA is the value introduced by this
    # migration and GUIA remains valid in the restored 0006 model state.
    Adulto.objects.filter(rol_principal="GUIADORA").update(rol_principal="GUIA")


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0006_alter_adulto_certificado_inhabilidades_and_more"),
        ("unidades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adulto",
            name="rol_principal",
            field=models.CharField(
                choices=[
                    ("GUIADORA", "Guiadora"),
                    ("DIRIGENTE", "Dirigente"),
                    ("APODERADO", "Apoderado"),
                    ("RESP_GRUPO", "Responsable de grupo"),
                    ("COLABORADOR", "Colaborador"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicaladulto",
            name="rol_principal",
            field=models.CharField(
                choices=[
                    ("GUIADORA", "Guiadora"),
                    ("DIRIGENTE", "Dirigente"),
                    ("APODERADO", "Apoderado"),
                    ("RESP_GRUPO", "Responsable de grupo"),
                    ("COLABORADOR", "Colaborador"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(regularize_adult_roles, reverse_regularize_adult_roles),
    ]
